import type { Material, Student, ClassGroup, Assignment, Badge, StudentBadge, XPTransaction } from "./types";

export const LEVEL_THRESHOLDS = [0, 100, 250, 450, 700, 1000, 1400, 1850, 2350, 3000, 3750, 4600, 5550, 6600, 7750];

export const MOCK_MATERIALS: Material[] = [
  {
    id: "mat-1",
    title: "Fotosinteza",
    subject: "Biologji",
    class: "VI-1",
    originalText:
      "Fotosinteza është procesi biologjik nëpërmjet të cilit bimët dhe organizmat e tjerë që përmbajnë klorofil shndërrojnë energjinë e dritës në energji kimike. Ky proces zhvillohet kryesisht në kloroplastet e gjendura në qelizat e gjetheve. Reagimi kryesor i fotosintezës mund të përmblidhet si: dioksidi i karbonit + uji + drita e diellit → glukoza + oksigjeni. Klorofili, pigmenti jeshil i bimëve, absorbon dritën e kuqe dhe blu, ndërsa reflekton dritën jeshile, duke i dhënë bimëve ngjyrën e tyre karakteristike.",
    simplifiedText:
      "Fotosinteza është mënyra si bimët krijojnë ushqimin e tyre. Bimët përdorin dritën e diellit, ujin dhe ajrin. Ky proces ndodh kryesisht në gjethe. Bimët marrin dioksid karboni nga ajri dhe ujë nga toka. Me ndihmën e dritës, ato prodhojnë sheqer si ushqim dhe lëshojnë oksigjen në ajër. Kjo është arsyeja pse bimët janë të rëndësishme për jetën tonë.",
    summary:
      "Bimët përdorin dritën e diellit për të prodhuar ushqim. Ky proces quhet fotosintezë dhe ndodh në gjethe.",
    keyPoints: [
      "Bimët kanë nevojë për dritë.",
      "Bimët thithin ujë nga toka.",
      "Fotosinteza ndodh kryesisht në gjethe.",
      "Bimët prodhojnë ushqimin e tyre vetë.",
      "Bimët lëshojnë oksigjen gjatë fotosintezës.",
    ],
    vocabulary: [
      {
        word: "Klorofili",
        definition: "Substanca jeshile e gjendur në gjethet e bimëve.",
        synonym: "Pigmenti jeshil",
        example: "Klorofili i bën gjethet të jenë jeshile.",
        translation: "Chlorophyll",
      },
      {
        word: "Energjia",
        definition: "Fuqia e nevojshme për të kryer një veprim.",
        synonym: "Forca",
        example: "Drita e diellit jep energji për bimët.",
        translation: "Energy",
      },
      {
        word: "Procesi",
        definition: "Një grup hapash nëpërmjet të cilëve ndodh diçka.",
        synonym: "Rruga",
        example: "Fotosinteza është një proces i rëndësishëm.",
        translation: "Process",
      },
    ],
    quiz: [
      {
        id: "q1",
        type: "multiple",
        question: "Ku ndodh kryesisht fotosinteza?",
        options: ["Në rrënjë", "Në gjethe", "Në lule", "Në trung"],
        correct: 1,
        hint: "Mendoni se ku është klorofili.",
        feedback:
          "Fotosinteza ndodh kryesisht në gjethe, ku ndodhet klorofili. Lexoni paragrafin e parë për më shumë.",
      },
      {
        id: "q2",
        type: "yesno",
        question: "A kanë nevojë bimët për dritë të diellit?",
        options: ["Po", "Jo"],
        correct: 0,
        hint: "Mendoni çfarë nuk mund të bëjnë bimët pa dritë.",
        feedback: "Saktë! Bimët kanë nevojë për dritë të diellit për të prodhuar ushqimin e tyre.",
      },
      {
        id: "q3",
        type: "multiple",
        question: "Çfarë prodhojnë bimët gjatë fotosintezës?",
        options: ["Ujë dhe dioksid karboni", "Sheqer dhe oksigjen", "Klorofil dhe ujë", "Azot dhe glukozë"],
        correct: 1,
        hint: "Bimët prodhojnë dy gjëra të rëndësishme.",
        feedback:
          "Gjatë fotosintezës, bimët prodhojnë sheqer si ushqim dhe lëshojnë oksigjen. Lexoni pjesën e tekstit të thjeshtësuar.",
      },
      {
        id: "q4",
        type: "mainidea",
        question: "Cila është ideja kryesore e kësaj pjese?",
        options: [
          "Bimët janë jeshile sepse kanë klorofil",
          "Bimët prodhojnë ushqimin e tyre duke përdorur dritën e diellit",
          "Fotosinteza ndodh vetëm gjatë natës",
          "Bimët marrin ushqim nga toka",
        ],
        correct: 1,
        hint: "Mendoni për temën kryesore të gjithë tekstit.",
        feedback:
          "Ideja kryesore është se bimët prodhojnë ushqimin e tyre duke përdorur dritën e diellit — ky quhet fotosintezë.",
      },
      {
        id: "q5",
        type: "short",
        question: "Çfarë është klorofili?",
        options: [],
        correct: "substanca jeshile",
        hint: "Çfarë i jep bimëve ngjyrën jeshile?",
        feedback: "Klorofili është substanca jeshile e gjendur në gjethet e bimëve që ndihmon fotosintezën.",
      },
    ],
    teacherNotes:
      "Ky material është i përshtatshëm për nxënësit e klasës VI. Rekomandohet leximi me zë i lartë. Vëmendje te fjala 'klorofil' — shumë nxënës e kanë të vështirë.",
    status: "published",
    createdAt: "2026-07-01",
    studentCount: 22,
    completionRate: 78,
    estimatedMinutes: 15,
  },
  {
    id: "mat-2",
    title: "Sistemi Diellor",
    subject: "Shkencë",
    class: "VI-2",
    originalText:
      "Sistemi Diellor përbëhet nga Dielli dhe të gjitha objektet qiellore që rrotullohen rreth tij.",
    simplifiedText: "Sistemi Diellor ka Diellin në qendër. Tetë planeta rrotullohen rreth tij.",
    summary: "Sistemi Diellor ka Diellin dhe 8 planeta.",
    keyPoints: ["Dielli është ylli ynë.", "Ka 8 planeta."],
    vocabulary: [],
    quiz: [],
    teacherNotes: "",
    status: "approved",
    createdAt: "2026-07-03",
    studentCount: 18,
    completionRate: 45,
    estimatedMinutes: 20,
  },
  {
    id: "mat-3",
    title: "Uji dhe Rrethet e Tij",
    subject: "Kimi",
    class: "VII-1",
    originalText: "Uji është një kompound kimik i formës H₂O.",
    simplifiedText: "Uji bëhet nga hidrogjeni dhe oksigjeni.",
    summary: "Uji është i rëndësishëm për jetën.",
    keyPoints: ["Uji nuk ka ngjyrë.", "Uji ngrin në 0°C."],
    vocabulary: [],
    quiz: [],
    teacherNotes: "",
    status: "draft",
    createdAt: "2026-07-05",
    studentCount: 0,
    completionRate: 0,
    estimatedMinutes: 12,
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: "stu-1",
    name: "Ardi Hoxha",
    class: "VI-1",
    age: 12,
    readingLevel: "Mesatar",
    score: 52,
    completedMaterials: 3,
    status: "needs-support",
    alertReason: "Vështirësi në identifikimin e idesë kryesore",
    preferredFont: "lexend",
    audioEnabled: true,
    language: "sq",
  },
  {
    id: "stu-2",
    name: "Sara Berisha",
    class: "VI-1",
    age: 11,
    readingLevel: "Bazik",
    score: 61,
    completedMaterials: 4,
    status: "needs-support",
    alertReason: "Kërkoi shumë shpjegime fjalësh",
    preferredFont: "atkinson",
    audioEnabled: true,
    language: "sq",
  },
  {
    id: "stu-3",
    name: "Dren Gashi",
    class: "VI-1",
    age: 12,
    readingLevel: "Mesatar",
    score: 57,
    completedMaterials: 2,
    status: "needs-support",
    alertReason: "Dy detyra të papërfunduara",
    preferredFont: "inter",
    audioEnabled: false,
    language: "sq",
  },
  {
    id: "stu-4",
    name: "Lira Krasniqi",
    class: "VI-1",
    age: 11,
    readingLevel: "Avancuar",
    score: 88,
    completedMaterials: 7,
    status: "excellent",
    preferredFont: "lexend",
    audioEnabled: false,
    language: "sq",
  },
  {
    id: "stu-5",
    name: "Besnik Morina",
    class: "VI-2",
    age: 12,
    readingLevel: "Mesatar",
    score: 74,
    completedMaterials: 5,
    status: "active",
    preferredFont: "inter",
    audioEnabled: true,
    language: "sq",
  },
  {
    id: "stu-6",
    name: "Vesa Kelmendi",
    class: "VI-2",
    age: 11,
    readingLevel: "Avancuar",
    score: 91,
    completedMaterials: 8,
    status: "excellent",
    preferredFont: "atkinson",
    audioEnabled: false,
    language: "sq",
  },
  {
    id: "stu-7",
    name: "Artan Rexhepi",
    class: "VII-1",
    age: 13,
    readingLevel: "Bazik",
    score: 63,
    completedMaterials: 3,
    status: "active",
    preferredFont: "lexend",
    audioEnabled: true,
    language: "sq",
  },
];

export const MOCK_CLASSES: ClassGroup[] = [
  { id: "cls-1", name: "Klasa VI-1", studentCount: 22, activeMaterials: 3, averageScore: 68 },
  { id: "cls-2", name: "Klasa VI-2", studentCount: 19, activeMaterials: 2, averageScore: 74 },
  { id: "cls-3", name: "Klasa VII-1", studentCount: 21, activeMaterials: 3, averageScore: 71 },
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: "asgn-1",
    materialId: "mat-1",
    studentId: "stu-1",
    deadline: "2026-07-15",
    startDate: "2026-07-01",
    allowRetry: true,
    showAnswers: true,
    enableAudio: true,
    status: "completed",
    score: 80,
    completedAt: "2026-07-10",
    timeSpentMinutes: 18,
    wordsOpened: 3,
    audioUsed: true,
    attempts: 2,
  },
  {
    id: "asgn-2",
    materialId: "mat-2",
    studentId: "stu-1",
    deadline: "2026-07-20",
    startDate: "2026-07-05",
    allowRetry: true,
    showAnswers: false,
    enableAudio: true,
    status: "in-progress",
    attempts: 1,
  },
  {
    id: "asgn-3",
    materialId: "mat-1",
    studentId: "stu-2",
    deadline: "2026-07-15",
    startDate: "2026-07-01",
    allowRetry: true,
    showAnswers: true,
    enableAudio: true,
    status: "pending",
  },
];

export const ALL_BADGES: Badge[] = [
  {
    id: "badge-1",
    name: "Hapi i Parë",
    description: "Përfundove materialin tënd të parë.",
    icon: "BookOpen",
    category: "reading",
    rarity: "common",
    conditionType: "materials_completed",
    conditionValue: 1,
    xpReward: 20,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-2",
    name: "Lexues Aktiv",
    description: "Përfundove 5 materiale mësimore.",
    icon: "BookMarked",
    category: "reading",
    rarity: "uncommon",
    conditionType: "materials_completed",
    conditionValue: 5,
    xpReward: 40,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-3",
    name: "Ndërtues i Fjalorit",
    description: "Mësove dhe përdore 20 fjalë të reja.",
    icon: "Library",
    category: "vocabulary",
    rarity: "uncommon",
    conditionType: "words_opened",
    conditionValue: 20,
    xpReward: 50,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-4",
    name: "Rezultat i Shkëlqyeshëm",
    description: "Arrite 100% në një kuiz.",
    icon: "Star",
    category: "quiz",
    rarity: "rare",
    conditionType: "perfect_score",
    conditionValue: 1,
    xpReward: 40,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-5",
    name: "Nivel i Ri",
    description: "Arrite Nivelin 5.",
    icon: "TrendingUp",
    category: "level",
    rarity: "uncommon",
    conditionType: "level_reached",
    conditionValue: 5,
    xpReward: 50,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-6",
    name: "Nuk Dorëzohem",
    description: "E përmirësove rezultatin pas një tentimi tjetër.",
    icon: "RefreshCw",
    category: "progress",
    rarity: "uncommon",
    conditionType: "improved_score",
    conditionValue: 1,
    xpReward: 30,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-7",
    name: "Dëgjues i Kujdesshëm",
    description: "Përdore audion për të përfunduar 5 materiale.",
    icon: "Headphones",
    category: "audio",
    rarity: "uncommon",
    conditionType: "audio_materials",
    conditionValue: 5,
    xpReward: 40,
    isAutomatic: true,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-t1",
    name: "Përpjekje e Jashtëzakonshme",
    description: "Ke treguar përpjekje dhe vendosmëri të madhe.",
    icon: "Award",
    category: "teacher",
    rarity: "teacher",
    conditionType: "teacher_awarded",
    xpReward: 30,
    isAutomatic: false,
    isSecret: false,
    isEnabled: true,
  },
  {
    id: "badge-t2",
    name: "Ylli i Klasës",
    description: "Mësuesi po të vlerëson për punën dhe përkushtimin tënd.",
    icon: "Sparkles",
    category: "teacher",
    rarity: "teacher",
    conditionType: "teacher_awarded",
    xpReward: 50,
    isAutomatic: false,
    isSecret: false,
    isEnabled: true,
  },
];

export const MOCK_STUDENT_BADGES: StudentBadge[] = [
  {
    id: "sb-1",
    studentId: "stu-1",
    badgeId: "badge-1",
    earnedAt: "2026-07-02",
    awardedBy: "system",
  },
  {
    id: "sb-2",
    studentId: "stu-1",
    badgeId: "badge-6",
    earnedAt: "2026-07-10",
    awardedBy: "system",
  },
  {
    id: "sb-3",
    studentId: "stu-1",
    badgeId: "badge-t1",
    earnedAt: "2026-07-08",
    awardedBy: "teacher",
    teacherId: "teacher-1",
    teacherMessage: "Ke bërë një përmirësim të madh në kuptimin e idesë kryesore. Vazhdo kështu!",
  },
];

export const MOCK_XP_TRANSACTIONS: XPTransaction[] = [
  {
    id: "xp-1",
    studentId: "stu-1",
    amount: 5,
    reason: "Hapi materialin 'Fotosinteza'",
    sourceType: "material",
    sourceId: "mat-1",
    awardedBy: "system",
    createdAt: "2026-07-02T09:00:00Z",
  },
  {
    id: "xp-2",
    studentId: "stu-1",
    amount: 30,
    reason: "Përfundoi materialin 'Fotosinteza'",
    sourceType: "material",
    sourceId: "mat-1",
    awardedBy: "system",
    createdAt: "2026-07-02T09:20:00Z",
  },
  {
    id: "xp-3",
    studentId: "stu-1",
    amount: 20,
    reason: "Plotësoi kuizin e 'Fotosintezës'",
    sourceType: "quiz",
    sourceId: "mat-1",
    awardedBy: "system",
    createdAt: "2026-07-02T09:35:00Z",
  },
  {
    id: "xp-4",
    studentId: "stu-1",
    amount: 20,
    reason: "Rezultat mbi 80%",
    sourceType: "quiz",
    sourceId: "mat-1",
    awardedBy: "system",
    createdAt: "2026-07-02T09:35:00Z",
  },
  {
    id: "xp-5",
    studentId: "stu-1",
    amount: 15,
    reason: "Përmirësoi rezultatin e mëparshëm",
    sourceType: "improvement",
    sourceId: "mat-1",
    awardedBy: "system",
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "xp-6",
    studentId: "stu-1",
    amount: 30,
    reason: "Shpërblim nga mësuesja Arta",
    sourceType: "teacher",
    awardedBy: "teacher",
    teacherId: "teacher-1",
    createdAt: "2026-07-08T11:00:00Z",
  },
];

export const WEEKLY_PROGRESS_DATA = [
  { week: "Javë 1", score: 58, completion: 60 },
  { week: "Javë 2", score: 63, completion: 70 },
  { week: "Javë 3", score: 67, completion: 75 },
  { week: "Javë 4", score: 71, completion: 80 },
  { week: "Javë 5", score: 74, completion: 85 },
];

export const SKILLS_DATA = [
  { name: "Kuptimi i tekstit", value: 74 },
  { name: "Fjalori", value: 68 },
  { name: "Ideja kryesore", value: 61 },
  { name: "Pyetje me zgjedhje", value: 82 },
];

export const ACTIVITY_ITEMS = [
  { id: "a1", text: "Ardi përfundoi kuizin 'Fotosinteza'", time: "5 min më parë", icon: "CheckCircle" },
  { id: "a2", text: "Sara kërkoi shpjegime për 4 fjalë", time: "12 min më parë", icon: "HelpCircle" },
  { id: "a3", text: "Materiali 'Sistemi Diellor' u aprovua", time: "1 orë më parë", icon: "CheckCircle" },
  { id: "a4", text: "5 nxënës përfunduan detyrën e fundit", time: "2 orë më parë", icon: "Users" },
];
